### ISSUE TITLE
Where is the API-bank-data.zip 

### ISSUE THREAD

**Issue by Hertzccc** [SMAT-Lab/SnifferDog#1]
Hi!
I recently read your paper and wanna try it on my computer. But I cannot find the API-bank-data.zip after the first step.

**Comment by Jarvx** [comment]
Thanks for your interests and  pointing this out ! The zip file has been uploaded. Please feel free to contact me if you encounter any problem. 
 
Best regards

**Comment by Hertzccc** [comment]
Thanks so much.
Good day



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 28, 2021 17:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SMAT-Lab/SnifferDog] Where is the API-bank-data.zip  (#1)




 
Thanks for your interests and  pointing this out ! The zip file has been uploaded. Please feel free to contact me if you encounter any problem.
 
Best regards
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
