### ISSUE TITLE
Error when executing lib_ver_producer.py: `core/util.py` is missing `get_code_list`

### ISSUE THREAD

**Issue by pcyin** [SMAT-Lab/SnifferDog#2]
When running `python lib_ver_producer.py` I got the following error:

```
ImportError: cannot import name 'get_code_list' from 'core.util'
```

It seems the function `get_code_list` is not defined in `core/util.py`.

**Comment by Jarvx** [comment]
Thanks for reporting this. Will fix it quite soon.

**Comment by Jarvx** [comment]
Thanks for raising this issue to us. I will now close it, please feel free to reopen if you have any questions.
