### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by Daniel-Mietchen** [SMAT-Lab/SnifferDog#3]
to clarify reusability

**Comment by Jarvx** [comment]
Thanks, will push the licence soon.

**Comment by astrojuanlu** [comment]
This would be the most restrictive one: https://github.com/SMAT-Lab/SnifferDog/community/license/new?branch=master&filename=LICENSE&template=agpl-3.0

And this would be a more commercial-friendly one: https://github.com/SMAT-Lab/SnifferDog/community/license/new?branch=master&filename=LICENSE&template=mit

**Comment by astrojuanlu** [comment]
Code is now Apache https://github.com/SMAT-Lab/SnifferDog/blob/master/LICENSE
