### ISSUE TITLE
API-Bank is destroyed

### ISSUE THREAD

**Issue by linli1724647576** [SMAT-Lab/SnifferDog#5]
Hi, SMAT-La, when I run SnifferDog, I find API-bank-data.zip.ZIP is destroyed.
![image](https://user-images.githubusercontent.com/51497456/199659351-c62aec9c-471f-4d53-a0bb-8416affb165b.png)

![image](https://user-images.githubusercontent.com/51497456/199659436-eb7032a9-796c-4627-a38b-df7d773d4e31.png)

Can you commit a new API-Bank? 
Thanks.

**Comment by Jarvx** [comment]
Hi 

Please use the download link to obtain the data file.

**Comment by astrojuanlu** [comment]
Indeed, git LFS cannot be used anymore:

```
> git lfs fetch
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/SMAT-Lab/SnifferDog.git/info/lfs'
```

**Comment by Jarvx** [comment]
> Indeed, git LFS cannot be used anymore:
> 
> ```
> > git lfs fetch
> fetch: Fetching reference refs/heads/master
> batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
> error: failed to fetch some objects from 'https://github.com/SMAT-Lab/SnifferDog.git/info/lfs'
> ```

Hi, thanks for your interest. Please download from the google drive link which you can find in README.
